version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  build-and-deploy:
    docker:
      - image: cimg/python:3.11-node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/setup
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - ~/node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: echo $FRONT_ENV | base64 -d > .env
      - run: npm run generate
      - run: rm .env
      - run:
          name: Deploy to S3
          command: aws s3 sync .output/public/ s3://${FRONT_S3_BUCKET_NAME} --exact-timestamps --delete
      - run:
          name: Clear CloudFront cache
          command: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

workflows:
  deploy-stg:
    jobs:
      - build-and-deploy:
          context: tsundokuplus-stg
          filters:
            branches:
              only: main
  deploy-prd:
    jobs:
      - build-and-deploy:
          context: tsundokuplus-prd
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
